import { ArrowRight, BadgeCheck, CarFront, Check, ShieldCheck, Store, Users, Wrench } from 'lucide-react'
import { Link } from 'react-router'

const plans = [
  { icon: CarFront, title: 'Individual Sellers', subtitle: 'Selling your personal car?', price: 'Free', features: ['1 active car listing', 'Up to 5 photos per car', 'Sale or rental listing', 'Direct enquiries from buyers', 'Upgrade anytime'], to: '/register/individual', action: 'Create Free Account' },
  { icon: Wrench, title: 'Self-employed Professionals', subtitle: 'Mechanics, detailers and specialists', price: 'Free', features: ['Automotive service profile', 'Multiple service categories', 'Set your location and coverage area', 'Receive direct enquiries', 'Can also list 1 car'], to: '/register/individual', action: 'Create Free Account' },
  { icon: Store, title: 'Showrooms, Garages & Agencies', subtitle: 'One plan for your whole business', price: 'MUR 1,000 / year', features: ['1 full calendar month free', 'Up to 20 active cars', 'Up to 15 photos per car', 'Automotive service profile included', 'Cars, rentals and services together'], to: '/register/business', action: 'Start Free Trial' },
]
export function SellersPage() {
  return <div className="mc-page">
    <section className="mc-page-hero mc-page-hero--sellers"><div className="mc-shell"><p className="mc-eyebrow">For sellers & professionals</p><h1>Grow Your<br />Automotive Business<br /><em>in Mauritius</em></h1><p>List your car, showcase your services and connect with thousands of local buyers. Simple. Affordable. Effective.</p><div className="mc-hero-actions"><Link className="mc-button" to="/register/individual">Create Your Account <ArrowRight /></Link><Link className="mc-button mc-button--outline" to="/for-sellers#plans">View our plans</Link></div></div></section>
    <section className="mc-trust-strip"><div className="mc-shell"><div><Users /><span><b>Grow visibility</b>Reach buyers island-wide</span></div><div><BadgeCheck /><span><b>One simple plan</b>Cars and services together</span></div><div><ShieldCheck /><span><b>Trusted marketplace</b>Reviewed quality profiles</span></div><div><Store /><span><b>Built for Mauritius</b>Direct local contact</span></div></div></section>
    <section id="plans" className="mc-section mc-shell"><div className="mc-section-title"><div><p className="mc-eyebrow">Clear and transparent</p><h2>Choose the plan that fits you</h2></div></div><div className="mc-plan-grid">{plans.map(({ icon: Icon, ...plan }, index) => <article key={plan.title} className={index === 2 ? 'is-featured' : ''}>{index === 2 && <span className="mc-plan-label">One month free</span>}<Icon /><h3>{plan.title}</h3><p>{plan.subtitle}</p><strong>{plan.price}</strong><ul>{plan.features.map((item) => <li key={item}><Check /> {item}</li>)}</ul><Link className="mc-button" to={plan.to}>{plan.action} <ArrowRight /></Link></article>)}</div></section>
    <section className="mc-how"><div className="mc-shell"><div className="mc-section-title"><div><p className="mc-eyebrow">Get started in five steps</p><h2>How it works</h2></div></div><ol className="mc-onboarding">{['Create your account', 'Complete your profile', 'Add your listings', 'Get approved', 'Reach more customers'].map((step, index) => <li key={step}><span>{index + 1}</span><b>{step}</b></li>)}</ol></div></section>
    <section className="mc-cta-band"><div className="mc-shell"><div><p className="mc-eyebrow">Move your business forward</p><h2>Join a growing automotive community</h2><p>Cars, services and opportunities across Mauritius.</p></div><Link className="mc-button" to="/register/business">Get started <ArrowRight /></Link></div></section>
  </div>
}
