import { ArrowRight, BadgeCheck, MapPin, Search, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router'
import { professionals, services } from '@/data/marketplace'

export function ServicesPage() {
  return <div className="mc-page">
    <section className="mc-page-hero mc-page-hero--services"><div className="mc-shell"><p className="mc-eyebrow">Automotive services in Mauritius</p><h1>Keep Your<br />Car Going <em>Further.</em></h1><p>Find trusted automotive professionals near you. Garages, tyre shops, detailing, bodywork, electronics and more.</p><div className="mc-inline-trust"><span><ShieldCheck /> Trusted & reviewed</span><span><MapPin /> Local experts</span><span><Users /> Direct contact</span></div></div></section>
    <section className="mc-shell mc-service-search"><div className="mc-tabs"><Link to="/cars">Find a Car</Link><button className="is-active">Find a Service</button></div><form><label><Search /><input placeholder="What service are you looking for?" /></label><label><MapPin /><select><option>All Mauritius</option><option>Black River</option><option>Moka</option><option>Grand Baie</option></select></label><button className="mc-button">Search</button></form><div className="mc-chips">Popular: {services.slice(0, 6).map((s) => <button key={s.name}>{s.name}</button>)}</div></section>
    <section className="mc-section mc-shell"><div className="mc-section-title"><div><p className="mc-eyebrow">Browse by category</p><h2>Service categories</h2></div><a href="#professionals">View all categories <ArrowRight /></a></div><div className="mc-service-grid mc-service-grid--large">{services.map((service) => <a href="#professionals" key={service.name}><span>{service.icon}</span><b>{service.name}</b><small>{service.description}</small><ArrowRight /></a>)}</div></section>
    <section id="professionals" className="mc-section mc-section--soft"><div className="mc-shell"><div className="mc-section-title"><div><p className="mc-eyebrow">Reviewed and ready</p><h2>Featured automotive professionals</h2></div></div><div className="mc-pro-grid">{professionals.map((pro) => <article key={pro.name}><img src={pro.image} alt="" /><div><span className="mc-verified"><BadgeCheck /> Verified</span><h3>{pro.name}</h3><p>{pro.service}</p><small><MapPin /> {pro.locality} / ★ {pro.rating}</small><Link to="/contact">Contact directly <ArrowRight /></Link></div></article>)}</div></div></section>
    <section className="mc-section mc-shell"><div className="mc-why-grid"><div><ShieldCheck /><h3>Verified professionals</h3><p>Profiles are reviewed before appearing publicly.</p></div><div><MapPin /><h3>Local experts</h3><p>Find specialist help close to home.</p></div><div><Sparkles /><h3>Simple contact</h3><p>Call or WhatsApp professionals directly.</p></div><div><Users /><h3>All in one place</h3><p>Cars and automotive expertise together.</p></div></div></section>
    <section className="mc-cta-band"><div className="mc-shell"><div><p className="mc-eyebrow">Grow with MoriCar</p><h2>Are you an automotive professional?</h2><p>Join MoriCar and reach customers across Mauritius.</p></div><Link to="/for-sellers" className="mc-button">List your business <ArrowRight /></Link></div></section>
  </div>
}
